---
title: explore-project-template
hero_image: images/banner.png
description: explore-project-template description
version: 4
listed: false
copyedit: false
last_tested: '2021-03-26'
steps:
- title: Introduction
- title: Skills and group management
- title: Mentoring styles
- title: Supporting all learners 
- title: Reflection
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
- title: Session resources
- title: Common programming languages
- title: Showcasing and reflection
- title: Resources for mentors
- title: Reflection 2
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
- title: What next?
